### ISSUE TITLE
[5.9.0] Could not find custom rule directory: 

### ISSUE THREAD

**Issue by Toilal** [palantir/tslint#3638]
### Bug Report

- __TSLint version__: 5.9.0 (no issue with previous version)
- __TypeScript version__: 2.6.2
- __Running TSLint via__: Node.js API (webpack tslint-loader)

#### TypeScript code being linted

Any TypeScript code with `tslint.json` configuration:

```json
{
    "extends": "tslint-config-standard",
    "rules": {}
}
```

#### Actual behavior

```
Module build failed: FatalError: Could not find custom rule directory: 
    at new FatalError (/home/toilal/idea-projects/vue-webpack-template/tests/default/node_modules/tslint/lib/error.js:27:28)
    at loadCachedRule (/home/toilal/idea-projects/vue-webpack-template/tests/default/node_modules/tslint/lib/ruleLoader.js:113:19)
    at /home/toilal/idea-projects/vue-webpack-template/tests/default/node_modules/tslint/lib/ruleLoader.js:75:82
    at Object.find (/home/toilal/idea-projects/vue-webpack-template/tests/default/node_modules/tslint/lib/utils.js:139:22)
    at findRule (/home/toilal/idea-projects/vue-webpack-template/tests/default/node_modules/tslint/lib/ruleLoader.js:75:17)
    at Object.loadRules (/home/toilal/idea-projects/vue-webpack-template/tests/default/node_modules/tslint/lib/ruleLoader.js:38:20)
    at Linter.getEnabledRules (/home/toilal/idea-projects/vue-webpack-template/tests/default/node_modules/tslint/lib/linter.js:215:29)
    at Linter.lint (/home/toilal/idea-projects/vue-webpack-template/tests/default/node_modules/tslint/lib/linter.js:98:33)
    at lint (/home/toilal/idea-projects/vue-webpack-template/tests/default/node_modules/tslint-loader/index.js:70:10)
    at Object.module.exports (/home/toilal/idea-projects/vue-webpack-template/tests/default/node_modules/tslint-loader/index.js:140:3)
```

**Comment by adidahiya** [comment]
This was caused by #3412. I've started working on a fix here https://github.com/palantir/tslint/pull/3640

**Comment by adidahiya** [comment]
tslint-loader was doing a strange thing, by the way, by supplying an empty string for `rulesDirectory` all the time: https://github.com/wbuchwalter/tslint-loader/blob/4d166651d916a0c43dd5a11099d6ff532350e27b/index.js#L59

**Comment by adidahiya** [comment]
I just published 5.9.1, can you try it?

**Comment by Toilal** [comment]
Fixed ! thanks :+1:

**Comment by Sedaj** [comment]
@adidahiya Hi. The issue still exist for me on version 5.9.1 

    "tslint": "5.9.1",
    "tslint-react": "3.5.1",

running as `tslint --fix -c tslint.json 'src/**/*.tsx'`

tslint.json 

    {
        "extends": ["tslint:latest", "tslint-react"],
        "rules": {
            "jsx-wrap-multiline": false
        }
    }

Thank you
