### ISSUE TITLE
Stack overflow when using "no-unused-variable": [true]

### ISSUE THREAD

**Issue by hdeshev** [palantir/tslint#668]
We started seeing this error after upgrading the NativeScript modules project to the TypeScript 1.6.2 compiler. For the time being we set the setting to false, but it'd be great if we can enable it again.

To reproduce the problem:

- pull the latest master of the NativeScript project [here](https://github.com/NativeScript/NativeScript) (or explicitly checkout [this commit](https://github.com/NativeScript/NativeScript/commit/fc9922914420e57696a58f0ffe5683840610930b))
- clean your `.tscache` folder
- `$ npm install `
- `$ grunt tslint:build`

Any help would be greatly appreciated!

**Comment by JKillian** [comment]
Hmm, seems like a problem! I'll look into it

**Comment by JKillian** [comment]
Possible related: https://github.com/Microsoft/TypeScript/issues/4859

**Comment by JKillian** [comment]
I believe this was fixed while ago, let me know if you encounter the issue again though

**Comment by hdeshev** [comment]
Tried with the latest tslint, grunt-ts, and typescript compiler in [this branch](https://github.com/NativeScript/NativeScript/tree/hdeshev/upgrade-tslint) and I still get a stack overflow:

```
$ grunt tslint:build --stack
Running "tslint:build" (tslint) task
Fatal error: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at isInsideWithStatementBody (/home/local/TELERIK/hdeshev/w/nativescript/node_modules/typescript/lib/typescript.js:26015:43)
    at Object.getTypeOfNode [as getTypeAtLocation] (/home/local/TELERIK/hdeshev/w/nativescript/node_modules/typescript/lib/typescript.js:26310:17)
    at getPropertySymbolFromTypeReference (/home/local/TELERIK/hdeshev/w/nativescript/node_modules/typescript/lib/typescript.js:47443:48)
    at /home/local/TELERIK/hdeshev/w/nativescript/node_modules/typescript/lib/typescript.js:47432:29
    at Object.forEach (/home/local/TELERIK/hdeshev/w/nativescript/node_modules/typescript/lib/typescript.js:887:30)
    at getPropertySymbolsFromBaseTypes (/home/local/TELERIK/hdeshev/w/nativescript/node_modules/typescript/lib/typescript.js:47430:24)
    at getPropertySymbolFromTypeReference (/home/local/TELERIK/hdeshev/w/nativescript/node_modules/typescript/lib/typescript.js:47450:29)
    at Object.forEach (/home/local/TELERIK/hdeshev/w/nativescript/node_modules/typescript/lib/typescript.js:887:30)
    at /home/local/TELERIK/hdeshev/w/nativescript/node_modules/typescript/lib/typescript.js:47433:32
    at Object.forEach (/home/local/TELERIK/hdeshev/w/nativescript/node_modules/typescript/lib/typescript.js:887:30)
```

**Comment by hdeshev** [comment]
TypeScript 1.8.2 seems to fix this issue (using latest tslint, of course). Thanks!
